[package]
name = "stream_plotter"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"

eframe = "0.31.1"
egui = "0.31.1"
egui-plotter = "0.4.0"

plotters = { version = "0.3.7", features = ["full_palette"] }

ringbuffer = "0.15.0"

strum = "0.27.1"
strum_macros = "0.27.1"