[package]
name = "stream_plotter"
version = "0.1.0"
edition = "2024"

[features]
telemetry = []

[dependencies]
crossbeam-channel = "0.5.16"

drone_consts = { path = "../drone_consts" }

eframe = "0.36.1"
egui = "0.36.1"
egui_plot = "0.37"

ringbuffer = "0.16.0"

serialport = "4.9.0"
strum = "0.27.1"

[profile.release]
debug = true